/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author Llewellyn Craddock
 */
public class AddCompetenceFrame extends javax.swing.JFrame {

    /**
     * Creates new form AddCompetenceFrame
     */
    public AddCompetenceFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CompetenceDetailPanel = new javax.swing.JScrollPane();
        CompetenceDetailTable = new javax.swing.JTable();
        HeadLabel = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        CompetenceDetailLabel = new javax.swing.JLabel();
        CompetenceOwnershipLabel = new javax.swing.JLabel();
        CompetenceOwnershipPanel = new javax.swing.JScrollPane();
        CompetenceOwnershipTable = new javax.swing.JTable();
        AddCompetenceLabel = new javax.swing.JLabel();
        AddCompetencePanel = new javax.swing.JScrollPane();
        AddCompetenceTable = new javax.swing.JTable();
        TimesheetLabel = new javax.swing.JLabel();
        TimesheetPanel = new javax.swing.JScrollPane();
        TimesheetTable = new javax.swing.JTable();
        CostLabel = new javax.swing.JLabel();
        CostPanel = new javax.swing.JScrollPane();
        CostTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        CompetenceDetailTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6"
            }
        ));
        CompetenceDetailTable.setCellSelectionEnabled(true);
        CompetenceDetailTable.setEditingColumn(1);
        CompetenceDetailTable.setEditingRow(1);
        CompetenceDetailTable.setRowHeight(60);
        CompetenceDetailPanel.setViewportView(CompetenceDetailTable);

        HeadLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        HeadLabel.setText("Add Competence:");

        btnAdd.setText("Add");

        btnBack.setText("Back to Editor");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        CompetenceDetailLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CompetenceDetailLabel.setText("Competence Details");

        CompetenceOwnershipLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CompetenceOwnershipLabel.setText("Competence Ownership");

        CompetenceOwnershipTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6"
            }
        ));
        CompetenceOwnershipTable.setCellSelectionEnabled(true);
        CompetenceOwnershipTable.setEditingColumn(1);
        CompetenceOwnershipTable.setEditingRow(1);
        CompetenceOwnershipTable.setRowHeight(60);
        CompetenceOwnershipPanel.setViewportView(CompetenceOwnershipTable);

        AddCompetenceLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        AddCompetenceLabel.setText("Applicability of competence");

        AddCompetenceTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6"
            }
        ));
        AddCompetenceTable.setCellSelectionEnabled(true);
        AddCompetenceTable.setEditingColumn(1);
        AddCompetenceTable.setEditingRow(1);
        AddCompetenceTable.setRowHeight(60);
        AddCompetencePanel.setViewportView(AddCompetenceTable);

        TimesheetLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TimesheetLabel.setText("Timesheet");

        TimesheetTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6"
            }
        ));
        TimesheetTable.setCellSelectionEnabled(true);
        TimesheetTable.setEditingColumn(1);
        TimesheetTable.setEditingRow(1);
        TimesheetTable.setRowHeight(60);
        TimesheetPanel.setViewportView(TimesheetTable);

        CostLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CostLabel.setText("Cost per person");

        CostTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6"
            }
        ));
        CostTable.setCellSelectionEnabled(true);
        CostTable.setEditingColumn(1);
        CostTable.setEditingRow(1);
        CostTable.setRowHeight(60);
        CostPanel.setViewportView(CostTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnBack)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAdd))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(HeadLabel)
                            .addComponent(CompetenceDetailPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 907, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CompetenceDetailLabel)
                            .addComponent(CompetenceOwnershipPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 907, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CompetenceOwnershipLabel)
                            .addComponent(AddCompetencePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 907, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AddCompetenceLabel)
                            .addComponent(TimesheetPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 907, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TimesheetLabel)
                            .addComponent(CostPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 907, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CostLabel))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(HeadLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CompetenceDetailLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CompetenceDetailPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CompetenceOwnershipLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CompetenceOwnershipPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(AddCompetenceLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AddCompetencePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(TimesheetLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TimesheetPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(CostLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CostPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnBack))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        MainFrame mf = new MainFrame ();
        mf.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddCompetenceFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddCompetenceFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddCompetenceFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddCompetenceFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddCompetenceFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AddCompetenceLabel;
    private javax.swing.JScrollPane AddCompetencePanel;
    private javax.swing.JTable AddCompetenceTable;
    private javax.swing.JLabel CompetenceDetailLabel;
    private javax.swing.JScrollPane CompetenceDetailPanel;
    private javax.swing.JTable CompetenceDetailTable;
    private javax.swing.JLabel CompetenceOwnershipLabel;
    private javax.swing.JScrollPane CompetenceOwnershipPanel;
    private javax.swing.JTable CompetenceOwnershipTable;
    private javax.swing.JLabel CostLabel;
    private javax.swing.JScrollPane CostPanel;
    private javax.swing.JTable CostTable;
    private javax.swing.JLabel HeadLabel;
    private javax.swing.JLabel TimesheetLabel;
    private javax.swing.JScrollPane TimesheetPanel;
    private javax.swing.JTable TimesheetTable;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBack;
    // End of variables declaration//GEN-END:variables
}
