/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Classes.DataLoad;
import Util.Debug;
import java.io.FileNotFoundException;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Llewellyn Craddock
 */
public class AddCompetenceFrame extends javax.swing.JFrame {

    /**
     * Creates new form AddCompetenceFrame
     */
    int unique;
    MainFrame mf = new MainFrame(0);

    public AddCompetenceFrame() {
        initComponents();
        this.InitializeTables();
        mf.setExtendedState(MainFrame.MAXIMIZED_BOTH);
        mf.setEnabled(false);
        mf.setVisible(true);
    }

    private void InitializeTables() {

        DataLoad data = new DataLoad();
        DefaultTableModel[] Arr;
        Arr = data.GenerateTableModel();
        unique = data.getUniqueCompetenceNumber();
        Debug.Log("Unique number is " + unique);

        CompetenceDetailTable.setModel(Arr[0]);
        CompetenceDetailTable.setValueAt(unique, 0, 0);
        String defaultText = "NA";
        for (int i = 1; i < CompetenceDetailTable.getColumnCount(); i++) {
            CompetenceDetailTable.setValueAt(defaultText, 0, i);
        }

        CompetenceOwnershipTable.setModel(Arr[1]);
        CompetenceOwnershipTable.setValueAt(unique, 0, 0);
        for (int i = 1; i < CompetenceOwnershipTable.getColumnCount(); i++) {
            CompetenceOwnershipTable.setValueAt(defaultText, 0, i);
        }

        AppCompetenceTable.setModel(Arr[2]);
        AppCompetenceTable.setValueAt(unique, 0, 0);
        for (int i = 1; i < AppCompetenceTable.getColumnCount(); i++) {
            AppCompetenceTable.setValueAt(defaultText, 0, i);
        }

        TimesheetTable.setModel(Arr[3]);
        TimesheetTable.setValueAt(unique, 0, 0);
        for (int i = 1; i < TimesheetTable.getColumnCount(); i++) {
            TimesheetTable.setValueAt(defaultText, 0, i);
        }

        CostTable.setModel(Arr[4]);
        CostTable.setValueAt(unique, 0, 0);
        int defaultNum = 0;
        for (int i = 1; i < CostTable.getColumnCount() - 1; i++) {
            CostTable.setValueAt(defaultNum, 0, i);
        }
        CostTable.setValueAt("N/A", 0, CostTable.getColumnCount() - 1);

        UniqueNumberLabel.setText("Your Unique Competence Matrix Number is: " + unique);

    }

    private String ConstructLine(String[] line) {
        String result = "";
        for (int i = 0; i < line.length; i++) {
            if (i == (line.length - 1)) {
                if ("null".equals(line[i])) {
                    result += "NA";
                } else {
                    result += line[i];
                }
            } else {
                if ("null".equals(line[i])) {
                    result += "NA" + "\t";
                } else {
                    result += line[i] + "\t";
                }
            }

        }
        Debug.Log(result);
        return result;
    }

    private String[] getTableData(JTable table) {
        DefaultTableModel dtm = (DefaultTableModel) table.getModel();
        int numCol = dtm.getColumnCount();
        String[] tableData = new String[numCol];
        for (int j = 0; j < numCol; j++) {
            tableData[j] = String.valueOf(dtm.getValueAt(0, j));
        }
        Debug.Log("Printing TableData::");
        return tableData;
    }

    private String[] ConstructArray() {

        String[] lineArr = new String[5];
        String[] line;

        line = this.getTableData(CompetenceDetailTable);
        lineArr[0] = this.ConstructLine(line);

        line = this.getTableData(CompetenceOwnershipTable);
        lineArr[1] = this.ConstructLine(line);

        line = this.getTableData(AppCompetenceTable);
        lineArr[2] = this.ConstructLine(line);

        line = this.getTableData(TimesheetTable);
        lineArr[3] = this.ConstructLine(line);

        line = this.getTableData(CostTable);
        lineArr[4] = this.ConstructLine(line);
        for (int i = 0; i < lineArr.length; i++) {
            if (lineArr[i] == null) {
                Debug.Log("Changing Null to NA");
                lineArr[i] = "NA";
            }
            Debug.Log(lineArr[i]);
        }

        return lineArr;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CompetenceDetailPanel = new javax.swing.JScrollPane();
        CompetenceDetailTable = new javax.swing.JTable();
        HeadLabel = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        CompetenceDetailLabel = new javax.swing.JLabel();
        CompetenceOwnershipLabel = new javax.swing.JLabel();
        CompetenceOwnershipPanel = new javax.swing.JScrollPane();
        CompetenceOwnershipTable = new javax.swing.JTable();
        AppCompetenceLabel = new javax.swing.JLabel();
        AppCompetencePanel = new javax.swing.JScrollPane();
        AppCompetenceTable = new javax.swing.JTable();
        TimesheetLabel = new javax.swing.JLabel();
        TimesheetPanel = new javax.swing.JScrollPane();
        TimesheetTable = new javax.swing.JTable();
        CostLabel = new javax.swing.JLabel();
        CostPanel = new javax.swing.JScrollPane();
        CostTable = new javax.swing.JTable();
        UniqueNumberLabel = new javax.swing.JLabel();

        setType(java.awt.Window.Type.UTILITY);

        CompetenceDetailTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6"
            }
        ));
        CompetenceDetailTable.setCellSelectionEnabled(true);
        CompetenceDetailTable.setEditingColumn(1);
        CompetenceDetailTable.setEditingRow(1);
        CompetenceDetailTable.setRowHeight(60);
        CompetenceDetailTable.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                CompetenceDetailTableKeyPressed(evt);
            }
        });
        CompetenceDetailPanel.setViewportView(CompetenceDetailTable);

        HeadLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        HeadLabel.setText("Add Competence:");

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnBack.setText("Back to Editor");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        CompetenceDetailLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CompetenceDetailLabel.setText("Competence Details");

        CompetenceOwnershipLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CompetenceOwnershipLabel.setText("Competence Ownership");

        CompetenceOwnershipTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6"
            }
        ));
        CompetenceOwnershipTable.setCellSelectionEnabled(true);
        CompetenceOwnershipTable.setEditingColumn(1);
        CompetenceOwnershipTable.setEditingRow(1);
        CompetenceOwnershipTable.setRowHeight(60);
        CompetenceOwnershipPanel.setViewportView(CompetenceOwnershipTable);

        AppCompetenceLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        AppCompetenceLabel.setText("Applicability of competence");

        AppCompetenceTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6"
            }
        ));
        AppCompetenceTable.setCellSelectionEnabled(true);
        AppCompetenceTable.setEditingColumn(1);
        AppCompetenceTable.setEditingRow(1);
        AppCompetenceTable.setRowHeight(60);
        AppCompetencePanel.setViewportView(AppCompetenceTable);

        TimesheetLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TimesheetLabel.setText("Timesheet");

        TimesheetTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6"
            }
        ));
        TimesheetTable.setCellSelectionEnabled(true);
        TimesheetTable.setEditingColumn(1);
        TimesheetTable.setEditingRow(1);
        TimesheetTable.setRowHeight(60);
        TimesheetPanel.setViewportView(TimesheetTable);

        CostLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CostLabel.setText("Cost per person");

        CostTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6"
            }
        ));
        CostTable.setCellSelectionEnabled(true);
        CostTable.setEditingColumn(1);
        CostTable.setEditingRow(1);
        CostTable.setRowHeight(60);
        CostPanel.setViewportView(CostTable);

        UniqueNumberLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        UniqueNumberLabel.setText("Your Unique Competence Matrix Number is: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnBack)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnAdd))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(CompetenceDetailPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 907, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(CompetenceOwnershipPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 907, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(CompetenceOwnershipLabel)
                                .addComponent(AppCompetencePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 907, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(AppCompetenceLabel)
                                .addComponent(TimesheetPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 907, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(TimesheetLabel)
                                .addComponent(CostPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 907, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(CostLabel)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CompetenceDetailLabel)
                            .addComponent(HeadLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(UniqueNumberLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(79, 79, 79))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(HeadLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CompetenceDetailLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(UniqueNumberLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(22, 22, 22)))
                .addComponent(CompetenceDetailPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CompetenceOwnershipLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CompetenceOwnershipPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(AppCompetenceLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AppCompetencePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(TimesheetLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TimesheetPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(CostLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CostPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnBack))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        try {
            mf.RefreshTable(0);
        } catch (FileNotFoundException ex) {
            Debug.LogException(ex);
        }
        mf.setEnabled(true);
        mf.setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        DataLoad.StoreData(this.ConstructArray());
        try {
            mf.RefreshTable(0);
        } catch (FileNotFoundException ex) {
            Debug.LogException(ex);
        }
        this.setVisible(false);
        mf.setEnabled(true);
        mf.setVisible(true);
    }//GEN-LAST:event_btnAddActionPerformed

    private void CompetenceDetailTableKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CompetenceDetailTableKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_CompetenceDetailTableKeyPressed
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AppCompetenceLabel;
    private javax.swing.JScrollPane AppCompetencePanel;
    private javax.swing.JTable AppCompetenceTable;
    private javax.swing.JLabel CompetenceDetailLabel;
    private javax.swing.JScrollPane CompetenceDetailPanel;
    private javax.swing.JTable CompetenceDetailTable;
    private javax.swing.JLabel CompetenceOwnershipLabel;
    private javax.swing.JScrollPane CompetenceOwnershipPanel;
    private javax.swing.JTable CompetenceOwnershipTable;
    private javax.swing.JLabel CostLabel;
    private javax.swing.JScrollPane CostPanel;
    private javax.swing.JTable CostTable;
    private javax.swing.JLabel HeadLabel;
    private javax.swing.JLabel TimesheetLabel;
    private javax.swing.JScrollPane TimesheetPanel;
    private javax.swing.JTable TimesheetTable;
    private javax.swing.JLabel UniqueNumberLabel;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBack;
    // End of variables declaration//GEN-END:variables
}
